import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import RootLayout from '@/components/Layout'
import Header from '@/components/Header'
import About from '@/components/About'
import Statistics from '@/components/Statistics'
import Services from '@/components/Services'




const Home= () => {
  return (
    <>
      <Head>
        <title>Arena Web Security</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header></Header>
        <About></About>
        <Statistics></Statistics>
        <Services></Services>
      </main>
    </>
  )
}
Home .getLayout=(page)=>{
 return  (<RootLayout>{page}</RootLayout>)
}
export default Home;
